### ISSUE TITLE
Here we go Again

### ISSUE THREAD

**Issue by Xexman** [spooknik/SkyrimSE-Linux-Modding#3]
Sorry i know this is like my 3 post . So a bit of background i got it all to run fine then moved mopy to my skyrim se folder . ran ~/".steam/root/compatibilitytools.d/skyrim-proton/proton" run Mopy/Wrye\ Bash.exe got that to install skyui and the unoffical patch, Enabled the mods then closed out. Reran skyrim se and  ~/".steam/root/compatibilitytools.d/skyrim-proton/proton" run skse64_loader.exe then it spits out :

[manjaro3@manjaro-pc Skyrim Special Edition]$ ~/".steam/root/compatibilitytools.d/skyrim-proton/proton" run skse64_loader.exe
ERROR: ld.so: object '/home/manjaro3/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/manjaro3/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Traceback (most recent call last):
  File "/home/manjaro3/.steam/root/compatibilitytools.d/skyrim-proton/proton", line 262, in <module>
    create_fonts_symlinks(prefix)
  File "/home/manjaro3/.steam/root/compatibilitytools.d/skyrim-proton/proton", line 242, in create_fonts_symlinks
    os.symlink(fname, lname)
FileNotFoundError: [Errno 2] No such file or directory: '/home/manjaro3/.steam/root/compatibilitytools.d/skyrim-proton/dist/share/fonts/LiberationSans-Regular.ttf' -> '/home/manjaro3/.local/share/Steam/steamapps/compatdata/489830/pfx//drive_c/windows/Fonts/arial.ttf'

**Comment by spooknik** [comment]
All good. I am happy to help. 

I've never encountered that error before. It's saying you're missing fonts, but this is an odd error because the download I made includes these fonts. You can check if there are fonts in `/home/manjaro3/.steam/root/compatibilitytools.d/skyrim-proton/dist/share/fonts/`

There should be the 4 font files called: 
```
LiberationMono-Regular.ttf
LiberationSans-Bold.ttf
LiberationSans-Regular.ttf
LiberationSerif-Regular.ttf
```

If they are not there, then download the attachment from this comment and put all of them in that folder. [Liberation-Fonts.zip](https://github.com/spooknik/SkyrimSE-Linux-Modding/files/3141842/Liberation-Fonts.zip)

If they are there, then run `ls -l ` in the terminal for this folder. I suspect something is up with your permissions . You should see something like this: 

```
-rw-r--r-- 1 user user 313464 May  1 08:58 LiberationMono-Regular.ttf
-rw-r--r-- 1 user user 405592 May  1 08:58 LiberationSans-Bold.ttf
-rw-r--r-- 1 user user 402112 May  1 08:58 LiberationSans-Regular.ttf
-rw-r--r-- 1 user user 383092 May  1 08:58 LiberationSerif-Regular.ttf
```

In the first column, if there are no 'r's, that's bad. The 'r' means that everyone has the ability to read the file at least. If this is the case then you've got problems with permissions.

**Comment by Xexman** [comment]
They are there and
 [manjaro3@manjaro-pc fonts]$ ls -l
total 1480
-rw-r--r-- 1 manjaro3 manjaro3 313464 May  2 19:50 LiberationMono-Regular.ttf
-rw-r--r-- 1 manjaro3 manjaro3 405592 May  2 19:50 LiberationSans-Bold.ttf
-rw-r--r-- 1 manjaro3 manjaro3 402112 May  2 19:50 LiberationSans-Regular.ttf
-rw-r--r-- 1 manjaro3 manjaro3 383092 May  2 19:50 LiberationSerif-Regular.ttf
[manjaro3@manjaro-pc fonts]$

**Comment by spooknik** [comment]
Next thing is check if `/home/manjaro3/.local/share/Steam/steamapps/compatdata/489830/pfx//drive_c/windows/Fonts/arial.ttf` exists. Run `ls -l  /home/manjaro3/.local/share/Steam/steamapps/compatdata/489830/pfx//drive_c/windows/Fonts` and see if you have `rw` permissions for this folder. 

You should be able to read and write files to your .local folder. If not, you've got some problems. 

Last thing to try would be to manually put `LiberationSans-Regular.ttf` in `/home/manjaro3/.local/share/Steam/steamapps/compatdata/489830/pfx//drive_c/windows/Fonts` and rename it to `arial.ttf` but this probably isn't the correct solution. I suspect you have a deeper problem with permissions.
